baseurl = "https://actividadesmarbella.netlyfy.app"
languageCode = "es-ES"
paginate = "9"
summaryLength = "20"
theme = "parsa-hugo"
title = "Actividades Marbella"
[[menu.main]]
name = "Rutas"
parent = "Actividades"
url = "https://www.actividadesmarbella.com/categories/rutas/"
weight = 3
[[menu.main]]
name = "Excursiones"
parent = "Actividades"
url = "https://www.actividadesmarbella.com/categories/excursiones"
weight = 2
[[menu.main]]
name = "Alquiler"
parent = "Actividades"
url = "https://www.actividadesmarbella.com/categories/alquiler"
weight = 1
[[menu.main]]
has-children = true
name = "Actividades"
url = "homepage/home-1"
weight = 2
[[menu.main]]
name = "Acerca de"
url = "about"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author_image = "images/motos-de-agua-actividades-marbella.jpg"
bio = "Las mejores actividades turísticas en Marbella y alrededores. Actividades acuáticas, tours de ciudad y montañas"
contact_form_action = ""
copyright = "Copyright &copy; 2022 ActividadesMarbella.com "
description = "Actividades en Marbella y alrededores, rutas, excursiones y alquileres en la perla de la Costa del Sol. Qué hacer en Marbella de actividades turísticas y las mejores cosas divertidas que podrás encontrar"
email = "actividades.marbella@gmail.com"
google_analitycs_id = "Your ID"
home = "Home"
layout = "1"
logo = "images/logo-peque2.png"
mobile = "+34604100862"
preloader = false
search = false
social = []
web = "www.actividadesmarbella.com"
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
